/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EduToken } from "./EduToken";
export type { TransactionRegistry } from "./TransactionRegistry";
