/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EduToken__factory } from "./EduToken__factory";
export { TransactionRegistry__factory } from "./TransactionRegistry__factory";
